lOAD DATA
TRUNCATE
INTO TABLE O5.BI_PROMO_SALE_wrk
FIELDS TERMINATED BY '|'
TRAILING NULLCOLS
(
  ORDERNUM          CHAR,
  PROMO_ID_01       CHAR,
  PROMO_ID_02       CHAR,
  PROMO_ID_03       CHAR,
  PROMO_ID_04       CHAR,
  PROMO_ID_05       CHAR,
  PROMO_ID_06       CHAR,
  PROMO_ID_07       CHAR,
  PROMO_ID_08       CHAR,
  PROMO_ID_09       CHAR,
  PROMO_ID_10       CHAR 
)
