OPTIONS (SKIP=1)
LOAD DATA
--INFILE '/home/cognos/TESTING/O5OC1217_WEB.csv'
APPEND
--TRUNCATE
INTO TABLE o5.stg_omniture_simon_ord_data
WHEN ORDER_ID != ""
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
        DATE_RECEIVE            "TO_DATE(:DATE_RECEIVE,'Month DD, YYYY')",
        ORDER_ID,
        SENT_STATUS             CONSTANT "N",
        STATUS_CHANGE_DATE      FILLER
)