--USer account

---Edata_exchange:

create index idx_user_addre_id1 on CUSTOMER_PROFILE_STAGE_O5_S5A ( EMAIL_ADDRESS,nvl(ZIPCODE,'00000'), NVL(ZIP4,'00000') )


--O5

  CREATE TABLE "CUSTOMER_PROFILE_STAGE_HISTORY"
   (	"CUSTOMER_ID" VARCHAR2(50 BYTE),
	"SOURCE_CD" VARCHAR2(50 BYTE),
	"EMPLOYEENBR" VARCHAR2(20 BYTE),
	"CUSTOMERTYPE" VARCHAR2(10 BYTE),
	"RECENCY_DATE_TIME" TIMESTAMP (6),
	"PREFIX" VARCHAR2(10 BYTE),
	"FIRSTNAME" VARCHAR2(60 BYTE),
	"MIDDLENAME" VARCHAR2(1 BYTE),
	"LASTNAME" VARCHAR2(60 BYTE),
	"GENDER" VARCHAR2(1 BYTE),
	"DOB" DATE,
	"PHONE_NUMBER" VARCHAR2(20 BYTE),
	"ADDR1" VARCHAR2(150 BYTE),
	"ADDR2" VARCHAR2(150 BYTE),
	"ADDR3" VARCHAR2(150 BYTE),
	"CITY" VARCHAR2(50 BYTE),
	"STATE" VARCHAR2(50 BYTE),
	"ZIPCODE" VARCHAR2(15 BYTE),
	"ZIP4" VARCHAR2(10 BYTE),
	"COUNTRY" VARCHAR2(50 BYTE),
	"ADDRESS_TYPE" VARCHAR2(3 BYTE),
	"ADDRESS_PRIORITY_TYPE_CD" VARCHAR2(1 BYTE),
	"EMAIL_ADDRESS" VARCHAR2(150 BYTE),
	"EMAIL_OPT_IND" VARCHAR2(3 BYTE),
	"PHONE_OPT_IND" VARCHAR2(3 BYTE),
	"ADDRESS_OPT_IND" VARCHAR2(3 BYTE),
	"PREFERRRED_LANGUAGE" NUMBER(6,0),
	"CREATE_DT" TIMESTAMP (6),
	"MODIFY_DT" TIMESTAMP (6),
	"REGISTERED_CUSTOMER" VARCHAR2(1 BYTE),
	"MORE_NUMBER" VARCHAR2(50 BYTE),
	"LOAD_TIMESTAMP" TIMESTAMP (6),
	"BANNER_ID" NUMBER(2,0),
	"ADDR_FIRST_NAME" VARCHAR2(60 BYTE),
	"ADDR_LAST_NAME" VARCHAR2(60 BYTE),
	"ADDR_PREFIX" VARCHAR2(10 BYTE),
	"ADDR_DEFAULT_TYPE" VARCHAR2(10 BYTE),
	"ADDR_MIDDLE_NAME" VARCHAR2(60 BYTE),
	"ADDR_SUFFIX" VARCHAR2(10 BYTE),
	"ADDR_PHONE_NO" VARCHAR2(20 BYTE),
	"ADDR_EXTERNAL_ID" VARCHAR2(150 BYTE),
	"ADDR_PHONE_COUNTRY_CODE_NO" NUMBER(5,0),
	"ADDR_PHONE_NO_TYPE_CD" VARCHAR2(1 BYTE),
	"CANADIAN_CUST" VARCHAR2(1 BYTE)
   )
  PARTITION BY RANGE ("CREATE_DT") INTERVAL (NUMTODSINTERVAL(50,'DAY'))
 (PARTITION "SYS_P0"  VALUES LESS THAN (TIMESTAMP' 2020-01-01 00:00:00') SEGMENT CREATION IMMEDIATE )
  TABLESPACE "O5_DATA"  ;

  ---

  --------------------------------------------------------
--  DDL for Table USER_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "O5"."USER_ACCOUNT"
   (	"USA_ID" VARCHAR2(50 BYTE),
	"USA_SOURCE_CD" VARCHAR2(50 BYTE),
	"USA_EMAIL" VARCHAR2(150 BYTE),
	"USA_CUSTOMER_TYPE" VARCHAR2(10 BYTE),
	"RECENCY_DATE_TIME" TIMESTAMP (6),
	"USA_PREFIX" VARCHAR2(10 BYTE),
	"USA_FIRST_NM" VARCHAR2(60 BYTE),
	"USA_MIDDLE_NM" VARCHAR2(1 BYTE),
	"USA_LAST_NM" VARCHAR2(60 BYTE),
	"USA_GENDER" VARCHAR2(1 BYTE),
	"USA_DOB" DATE,
	"USA_EMPLOYEENBR" VARCHAR2(20 BYTE),
	"EMAIL_OPT_IND" VARCHAR2(3 BYTE),
	"PREFERRRED_LANGUAGE" NUMBER(6,0),
	"REGISTERED_CUSTOMER" VARCHAR2(1 BYTE),
	"MORE_NUMBER" VARCHAR2(50 BYTE),
	"BANNER_ID" NUMBER(2,0),
	"USA_PRFRD_ADDR1" VARCHAR2(150 BYTE),
	"USA_PRFRD_ADDR2" VARCHAR2(150 BYTE),
	"USA_PRFRD_ADDR3" VARCHAR2(150 BYTE),
	"USA_PRFRD_CITY" VARCHAR2(50 BYTE),
	"USA_PRFRD_STATE" VARCHAR2(50 BYTE),
	"USA_PRFRD_ZIPCODE" VARCHAR2(15 BYTE),
	"USA_PRFRD_ZIP4" VARCHAR2(10 BYTE),
	"USA_PRFRD_COUNTRY" VARCHAR2(50 BYTE),
	"USA_PHONE_NUMBER" VARCHAR2(20 BYTE),
	"USA_PHONE_OPT_IND" VARCHAR2(3 BYTE),
	"UCID_CREATE_DT" TIMESTAMP (6),
	"UCID_MODIFY_DT" TIMESTAMP (6),
	"DDW_CRT_TS" DATE,
	"DDW_MOD_TS" DATE,
	"LOYALITY_NUMBER" VARCHAR2(20 BYTE),
	"MIGRATED_REC" VARCHAR2(1 BYTE),
	"USA_PRFRD_ADDR_FIRST_NAME" VARCHAR2(60 BYTE),
	"USA_PRFRD_ADDR_LAST_NAME" VARCHAR2(60 BYTE),
	"USA_PRFRD_ADDR_PREFIX" VARCHAR2(10 BYTE),
	"USA_PRFRD_ADDR_DEFAULT_TYPE" VARCHAR2(10 BYTE),
	"USA_PRFRD_ADDR_MIDDLE_NAME" VARCHAR2(60 BYTE),
	"USA_PRFRD_ADDR_SUFFIX" VARCHAR2(60 BYTE),
	"USA_PRFRD_ADDR_PHONE_NO" VARCHAR2(20 BYTE),
	"USA_PRFRD_ADDR_EXTERNAL_ID" VARCHAR2(150 BYTE),
	"ADDR_PHONE_COUNTRY_CODE_NO" NUMBER(5,0),
	"USA_PRFRD_PHONE_TYPE_CD" VARCHAR2(10 BYTE),
	"USA_ADD_PRIOR_TYPE_CD" VARCHAR2(20 BYTE),
	"USA_PRFRD_ADDR_ACTIVEIND" VARCHAR2(20 BYTE),
	"CANADIAN_CUST" VARCHAR2(4 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 ROW STORE COMPRESS ADVANCED LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "O5_DATA" ;
--------------------------------------------------------
--  DDL for Index IDX_USER_ACCOUNT_EMAIL_CUSTID
--------------------------------------------------------

  CREATE INDEX "O5"."IDX_USER_ACCOUNT_EMAIL_CUSTID" ON "O5"."USER_ACCOUNT" ("USA_EMAIL", "USA_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "O5_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00278997
--------------------------------------------------------

  CREATE UNIQUE INDEX "O5"."SYS_C00278997" ON "O5"."USER_ACCOUNT" ("USA_EMAIL")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "O5_DATA" ;
--------------------------------------------------------
--  Constraints for Table USER_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "O5"."USER_ACCOUNT" ADD UNIQUE ("USA_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "O5_DATA"  ENABLE;

---

drop table USER_ADDRESS

 CREATE TABLE "O5"."USER_ADDRESS"
   (	"ADDRESS_ID" NUMBER DEFAULT "O5"."USER_ADDRESS_ID_SEQ"."NEXTVAL",
	"USA_ADDR1" VARCHAR2(150 BYTE),
	"USA_ADDR2" VARCHAR2(150 BYTE),
	"USA_ADDR3" VARCHAR2(150 BYTE),
	"USA_CITY" VARCHAR2(50 BYTE),
	"USA_STATE" VARCHAR2(50 BYTE),
	"USA_ZIPCODE" VARCHAR2(15 BYTE),
	"USA_ZIP4" VARCHAR2(10 BYTE),
	"USA_COUNTRY" VARCHAR2(50 BYTE),
	"USA_PHONE_NUMBER" VARCHAR2(20 BYTE),
	"USA_PHONE_OPT_IND" VARCHAR2(3 BYTE),
	"ADDRESS_TYPE" VARCHAR2(3 BYTE),
	"ADDRESS_PRIORITY_TYPE_CD" VARCHAR2(1 BYTE),
	"USA_EMAIL" VARCHAR2(150 BYTE),
	"UCID_CREATE_DT" TIMESTAMP (6),
	"UCID_MODIFY_DT" TIMESTAMP (6),
	"DDW_CRT_TS" DATE,
	"DDW_MOD_TS" DATE,
	"ADDR_FIRST_NAME" VARCHAR2(60 BYTE),
	"ADDR_LAST_NAME" VARCHAR2(60 BYTE),
	"ADDR_PREFIX" VARCHAR2(10 BYTE),
	"ADDR_DEFAULT_TYPE" VARCHAR2(10 BYTE),
	"ADDR_PHONE_NO" VARCHAR2(20 BYTE),
	"ADDR_EXTERNAL_ID" VARCHAR2(150 BYTE),
	"ADDR_PHONE_NO_TYPE_CD" VARCHAR2(1 BYTE),
	"ADDR_PHONE_COUNTRY_CODE_NO" NUMBER(5,0),
	"ADDR_MIDDLE_NAME" VARCHAR2(60 BYTE),
	"ADDR_SUFFIX" VARCHAR2(10 BYTE),
	"ADDRESS_OPT_IND" VARCHAR2(3 BYTE),
	"USA_ID" VARCHAR2(50 BYTE),
	"USA_FIRST_NM" VARCHAR2(60 BYTE),
	"USA_LAST_NM" VARCHAR2(60 BYTE),
	"ADDR_STATUS" VARCHAR2(3 BYTE),
	 FOREIGN KEY ("USA_EMAIL")
	  REFERENCES "O5"."USER_ACCOUNT" ("USA_EMAIL") ENABLE
   )
  TABLESPACE "O5_DATA" ;

  create index idx_user_addre_id2 on USER_ADDRESS ( USA_EMAIL,nvl(USA_ZIPCODE,'00000'), NVL(USA_ZIP4,'00000') )

  grant all on USER_ADDRESS to dm_user;
grant all on USER_ACCOUNT to dm_user;
grant all on USER_ACCOUNT_EXCEPTION to dm_user;

  --
  create or replace Function F_GET_ALT_IMAGE_URL (styl_seq_num  varchar2) return varchar2
is
v_out varchar2(32000) default null;
begin
 select alt_image_url  into v_out from o5.image_alt_o5
 where product_id = styl_seq_num;
 return rtrim(v_out);
  exception
when others then null;
return sqlerrm;
End;
