----O5----

CREATE TABLE "O5"."RFS_UDA_DATA"
 (	"SKN_NO" NUMBER(8,0) NOT NULL ENABLE,
"UDA_ID" NUMBER(5,0) NOT NULL ENABLE,
"LAST_MOD_DATE" DATE,
"UDA_VALUE" NUMBER(3,0) NOT NULL ENABLE,
"UDA_VALUE_DESC" VARCHAR2(250 BYTE) NOT NULL ENABLE,
"VALUE_LAST_MOD_DATE" DATE
 );


CREATE SEQUENCE INV_BATCH_SEQ MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1;


  CREATE TABLE "O5"."INVENTORY" 
   (	"SKN_NO" NUMBER(20,0) NOT NULL ENABLE, 
	"IN_STOCK_SELLABLE_QTY" NUMBER(10,0) NOT NULL ENABLE, 
	"IN_STOCK_UPDATE_DATE" DATE, 
	"ADD_DT" DATE, 
	"IN_STORE_QTY" NUMBER(18,0), 
	"WH_PO_DATE" DATE, 
	"WH_PO_NUMBER" NUMBER(38,0)
   ) ;

ALTER TABLE INVENTORY ADD (IN_STORE_UPDATE_DATE DATE);

CREATE INDEX "O5"."IDX_INVENTORY_1" ON "O5"."INVENTORY" ("SKN_NO") ;


  CREATE TABLE "O5"."INVENTORY_V1" 
   (	"ITEMID" VARCHAR2(20 BYTE), 
	"ALLOCATION" VARCHAR2(100 BYTE), 
	"ONHAND" NUMBER, 
	"ALLOCATIONTIMESTAMP" VARCHAR2(50 BYTE), 
	"BACKORDER" VARCHAR2(10 BYTE), 
	"DUMMY" VARCHAR2(10 BYTE), 
	"INSTOCKDATE" VARCHAR2(50 BYTE), 
	"PERPETUAL" VARCHAR2(10 BYTE), 
	"PREORDER" VARCHAR2(10 BYTE), 
	"PROCESSED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"BATCH_ID" NUMBER(18,0), 
	"ADD_DT" DATE DEFAULT SYSDATE
   ) 
PARTITION BY RANGE ("ADD_DT") INTERVAL (NUMTODSINTERVAL(1, 'DAY')) 
 (PARTITION "INV_V1_P0"  VALUES LESS THAN (TO_DATE(' 2018-08-26 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'));



CREATE INDEX "O5"."IDX_INVENTORY_V1" ON "O5"."INVENTORY_V1" ("ITEMID") ;

CREATE INDEX "O5"."IDX_INV_PRCSD" ON "O5"."INVENTORY_V1" (trunc("ADD_DT"),"PROCESSED") LOCAL ;


  CREATE TABLE "O5"."TECH_EXCPTN" 
   (	"PROCESS_NM" VARCHAR2(100 BYTE), 
	"KEY_ID" VARCHAR2(500 BYTE), 
	"ERROR_CD" VARCHAR2(500 BYTE), 
	"ERR_MSG" VARCHAR2(4000 BYTE), 
	"EXCPT_DT" DATE, 
	"BATCH_ID" NUMBER(18,0)
   );


CREATE INDEX "O5"."IDX_T_EXCPT" ON "O5"."TECH_EXCPTN" ("BATCH_ID") ;

  CREATE TABLE "O5"."INVENTORY_STORES" 
   (	"SKN_NO" NUMBER(20,0) NOT NULL ENABLE, 
     STORE_ID NUMBER(18,0),
	"ADD_DT" DATE, 
	"IN_STORE_QTY" NUMBER(18,0), 
    "IN_STORE_UPDATE_DATE" DATE,
	"BATCH_ID" NUMBER(18,0), 
	"MERGE_BATCH_ID" NUMBER(18,0)
   );


create index idx_inv_store_item on INVENTORY_STORES (STORE_ID,SKN_NO);

create index idx_inv_store_skn on INVENTORY_STORES (SKN_NO);
